<?php

namespace Best\ElasticSearch\Hercules\Queries;

use Best\ElasticSearch\Hercules\Type\Query;

class MatchPhrase extends Query
{
    /**
     * @var string
     */
    protected $analyzer;

    public function __construct()
    {
        // TODO
    }

    /**
     * @return array
     */
    public function toArray()
    {
        return parent::toArray(); // TODO: Change the autogenerated stub
    }

    /**
     *
     * @param string $analyzer
     * @return MatchPhrase
     */
    public function analyzer($analyzer)
    {
        $this->analyzer = $analyzer;
        return $this;
    }
}