<?php

namespace Best\ElasticSearch\Hercules\Queries;

use Best\ElasticSearch\Hercules\Type\Analyzer;
use Best\ElasticSearch\Hercules\Type\QueryInterface;

class MatchPhrase implements QueryInterface
{
    /**
     * @var string
     */
    protected $analyzer;

    public function __construct()
    {
        // TODO
    }

    /**
     * @return array
     */
    public function toArray()
    {
        // TODO: Change the autogenerated stub
    }

    /**
     *
     * @param Analyzer $analyzer
     * @return MatchPhrase
     */
    public function analyzer(Analyzer $analyzer)
    {
        $this->analyzer = $analyzer;
        return $this;
    }
}